spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: book
    password: book
  flyway:
    baselineOnMigrate: true
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


