spring:
  application:
    name: demo
  data:
    mongodb:
      url: mongodb://localhost:27017/book
      username: book
      password: book
      database: book
  flyway:
    baselineOnMigrate: true
    enabled: false


